{% set name = "model_bakery" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e44f5d58f11a8e1f733264f3d3659bd8e6d9c731779f91a3c70281df5066cd2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django >=1.11.0
    - python >=3.6

test:
  imports:
    - model_bakery

about:
  home: http://github.com/model-bakers/model_bakery
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Smart object creation facility for Django.
  doc_url: https://pypi.org/project/model-bakery/
  dev_url: https://github.com/model-bakers/model_bakery

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
