{% set name = "model_bakery" %}
{% set version = "1.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/model_bakery-{{ version }}.tar.gz
  sha256: 4e44f5d58f11a8e1f733264f3d3659bd8e6d9c731779f91a3c70281df5066cd2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - django >=2.2<4.0
    - python

test:
  imports:
    - model_bakery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/model-bakers/model_bakery
  summary: Smart object creation facility for Django.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BubblyOrca
